version: '3.1'

services:
  oneiot-server:
    container_name: oneiot-server  # Prevent duplicate containers
    image: oneiot-server  # Use your built app image, not `golang`
    ports:
      - "8000:8000"
    restart: unless-stopped  # Auto-restart if it crashes
